export const dictionaries = {
  en: {
    common: {
      title: "AUDIO SPECTRUM",
      upload: "Upload Audio",
      delete: "Delete",
      render: "Render Video",
      cancel: "Cancel",
      processing: "Processing...",
      idle: "Idle",
      done: "Done",
      error: "Error",
      seconds: "s",
    },
    controls: {
      playback: "Playback Controls",
      visualizer: "Visualizer Settings",
      sectionLayout: "Layout",
      sectionPositiveWave: "Positive Wave",
      sectionNegativeWave: "Negative Wave",
      sectionGlobal: "Global",
      sectionDynamics: "Dynamics",
      barCount: "Bar Count",
      barWidth: "Bar Width",
      spacing: "Spacing",
      totalWidth: "Total Width",
      heightScale: "Height Scale",
      color: "Color",
      gain: "Gain",
      cornerRadius: "Radius",
      contrast: "Contrast",
      attack: "Attack",
      decay: "Decay",
      yOffset: "Y Offset",
      barHeight: "Height Multiplier",
      ceiling: "Ceiling",
      strength: "Strength",
      renderFps: "Render FPS",
      encoder: "Encoder",
      resetAll: "Reset All",
      encoderDescription: {
        webcodecHardware:
          "Fastest hardware-based encoding. Draws directly from the canvas element.",
        webcodecSoftware:
          "Fast CPU-based software encoding. Draws directly from the canvas element.",
        ffmpeg:
          "Slowest CPU-based encoding using FFmpeg and libass. Frames are generated by libass and encoded by FFmpeg. Used purely as a fallback.",
      },
      referenceFps: "Reference FPS",
      frequencyRange: "Frequency Range",
    },
    drawer: {
      audioFiles: "Audio Files",
      renderQueue: "Render Queue",
      noFiles: "No audio files uploaded.",
      noTasks: "Queue is empty.",
      removeTask: "Remove Task?",
      cancelRendering: "Cancel Rendering?",
      removeTaskConfirm:
        "Are you sure you want to remove this task from the queue?",
      cancelTaskConfirm:
        "Are you sure you want to cancel this task? All processed data will be lost and cannot be recovered.",
      keepIt: "Keep It",
      yesRemove: "Yes, Remove",
      yesCancel: "Yes, Cancel",
    },
  },
  zh: {
    common: {
      title: "音頻頻譜美化器",
      upload: "上傳音頻",
      delete: "刪除",
      render: "渲染影片",
      cancel: "取消",
      processing: "處理中...",
      idle: "待處理",
      done: "已完成",
      error: "出錯",
      seconds: "秒",
    },
    controls: {
      playback: "播放控制",
      visualizer: "視覺化設定",
      sectionLayout: "排版",
      sectionPositiveWave: "正向波形",
      sectionNegativeWave: "負向波形",
      sectionGlobal: "全域",
      sectionDynamics: "動態壓縮",
      barCount: "條數",
      barWidth: "條寬",
      spacing: "間距",
      totalWidth: "總寬度",
      heightScale: "高度比例",
      color: "顏色",
      gain: "高度倍數",
      cornerRadius: "圓角",
      contrast: "對比度",
      attack: "衝力",
      decay: "掉落緩衝",
      yOffset: "垂直位移",
      barHeight: "高度倍率",
      ceiling: "天花板",
      strength: "強度",
      renderFps: "渲染幀率",
      encoder: "編碼器",
      resetAll: "全部重置",
      encoderDescription: {
        webcodecHardware: "最快，使用硬體渲染。直接從前端的canvas元素繪製。",
        webcodecSoftware:
          "快，使用CPU渲染，在硬體不可用時的備用選項。直接從前端的canvas元素繪製。",
        ffmpeg:
          "很慢，先用libass生成每一幀再用ffmpeg編碼，編碼階段極耗時。純粹作為最後選項。",
      },
      referenceFps: "計算繪製採樣率",
      frequencyRange: "波形頻率範圍",
    },
    drawer: {
      audioFiles: "音頻庫",
      renderQueue: "渲染隊列",
      noFiles: "尚未上傳任何音頻",
      noTasks: "隊列目前為空。",
      removeTask: "移除任務？",
      cancelRendering: "取消渲染？",
      removeTaskConfirm: "確定要從隊列中移除此任務嗎？",
      cancelTaskConfirm:
        "確定要取消此任務嗎？所有已處理的資料將遺失，無法恢復。",
      keepIt: "保留",
      yesRemove: "確認移除",
      yesCancel: "確認移除",
    },
  },
}

export type Locale = keyof typeof dictionaries
export type Dictionary = typeof dictionaries.en

export const getDictionary = (lang: string): Dictionary => {
  return (dictionaries as any)[lang] || dictionaries.en
}
