import { VisualizerSettings } from "../types"

export function generateASSHeader(width: number, height: number, title: string = "AudioVisualizer"): string {
  return `[Script Info]
; Script generated by Audio Spectrum Visualizer
Title: ${title}
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: ${width}
PlayResY: ${height}

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Roboto,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0,0,5,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`
}

function formatTime(seconds: number): string {
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  const s = Math.floor(seconds % 60)
  const ms = Math.floor((seconds % 1) * 100)
  return `${h}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}.${ms.toString().padStart(2, "0")}`
}

function hexToAssColor(hex: string): string {
  if (!hex.startsWith("#")) return "&HFFFFFF&"
  const r = hex.slice(1, 3)
  const g = hex.slice(3, 5)
  const b = hex.slice(5, 7)
  return `&H00${b}${g}${r}&`
}

export function generateASSFrame(
  startTime: number,
  endTime: number,
  heights: number[],
  settings: VisualizerSettings,
  width: number,
  height: number
): string {
  const totalContentWidth = settings.spacing * settings.barCount
  const startX = (width - totalContentWidth) / 2
  const centerY = height / 2 - (settings.yOffset || 0)
  const maxBarHeight = height * 0.45

  let events = ""
  const timeStartStr = formatTime(startTime)
  const timeEndStr = formatTime(endTime)

  if (settings.positiveHeightScale > 0) {
    let path = ""
    for (let i = 0; i < heights.length; i++) {
      const val = heights[i]
      const hPos = Math.max(0, val * maxBarHeight * settings.positiveHeightScale)
      if (hPos > 0.5) {
        const x = startX + i * settings.spacing + (settings.spacing - settings.barWidth) / 2
        const y = centerY - hPos
        path += ` m ${Math.round(x)} ${Math.round(y)} l ${Math.round(x + settings.barWidth)} ${Math.round(y)} l ${Math.round(x + settings.barWidth)} ${Math.round(centerY)} l ${Math.round(x)} ${Math.round(centerY)}`
      }
    }
    if (path) {
      events += `Dialogue: 0,${timeStartStr},${timeEndStr},Default,,0,0,0,,{\\an7\\pos(0,0)\\c${hexToAssColor(settings.positiveColor)}}{\\p1}${path}{\\p0}\n`
    }
  }

  if (settings.negativeHeightScale > 0) {
    let path = ""
    for (let i = 0; i < heights.length; i++) {
      const val = heights[i]
      const hNeg = Math.max(0, val * maxBarHeight * settings.negativeHeightScale)
      if (hNeg > 0.5) {
        const x = startX + i * settings.spacing + (settings.spacing - settings.barWidth) / 2
        const y = centerY
        path += ` m ${Math.round(x)} ${Math.round(y)} l ${Math.round(x + settings.barWidth)} ${Math.round(y)} l ${Math.round(x + settings.barWidth)} ${Math.round(y + hNeg)} l ${Math.round(x)} ${Math.round(y + hNeg)}`
      }
    }
    if (path) {
      events += `Dialogue: 0,${timeStartStr},${timeEndStr},Default,,0,0,0,,{\\an7\\pos(0,0)\\c${hexToAssColor(settings.negativeColor)}}{\\p1}${path}{\\p0}\n`
    }
  }

  return events
}
